CI: use multi-job workflow for publish-docker-images.yml.
- if `Pull gitea image with current submodule SHA` step failed, only the following step, `Push gitea to GitHub Container Registry` runs and all other steps gets cancelled
- A possible solution would be to add `always()` condition in all the proceeding steps but this is a lot of noise, and sometimes cancelling all jobs might be needed, so instead use multi-job workflow.

diff --git a/.github/workflows/publish-docker-images.yml b/.github/workflows/publish-docker-images.yml
--- a/.github/workflows/publish-docker-images.yml
+++ b/.github/workflows/publish-docker-images.yml
@@ -1,36 +1,37 @@
 name: Publish Docker images
+env:
+  POSTGRES_PASSWORD: change_me
+  KITSPACE_DOMAIN: kitspace.test
+  KITSPACE_SCHEME: http
+  KITSPACE_DEV_PORT: 3000
+  KITSPACE_EXTERNAL_PORT: ':3000'
+  CERTBOT_EMAIL: you@example.com
+  COMPOSE_PROJECT_NAME: kitspace
+  CYPRESS_GITEA_ADMIN_USERNAME: __admin
+  CYPRESS_GITEA_ADMIN_PASSWORD: 123456
+  FAIL_FAST_ENABLED: true
+  INDEX_ISR_INTERVAL: 3600
+  USER_ISR_INTERVAL: 86400
+  MAX_FILE_SIZE: 6M
+
 on:
   release:
-    types: [published]
+    types: [ published ]
   push:
     branches:
       - master
       - ghcr
 jobs:
-  push_to_registry:
-    name: Push Docker images to GitHub Container Register
+  push_to_registry_sha:
+    name: Push Docker images-SHA to GitHub Container Register
     runs-on: ubuntu-20.04
-    env:
-      POSTGRES_PASSWORD: change_me
-      KITSPACE_DOMAIN: kitspace.test
-      KITSPACE_SCHEME: http
-      KITSPACE_DEV_PORT: 3000
-      KITSPACE_EXTERNAL_PORT: ':3000'
-      CERTBOT_EMAIL: you@example.com
-      COMPOSE_PROJECT_NAME: kitspace
-      CYPRESS_GITEA_ADMIN_USERNAME: __admin
-      CYPRESS_GITEA_ADMIN_PASSWORD: 123456
-      FAIL_FAST_ENABLED: true
-      INDEX_ISR_INTERVAL: 3600
-      USER_ISR_INTERVAL: 86400
-      MAX_FILE_SIZE: 6M
 
     steps:
       - name: Check out the repo
         uses: actions/checkout@v2
         with:
           submodules: 'recursive'
-     
+
       - name: Get commit SHA
         id: sha
         shell: bash
@@ -41,7 +42,7 @@ jobs:
 
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v1
-      
+
       - name: Cache Docker layers
         uses: actions/cache@v2
         with:
@@ -49,14 +50,14 @@ jobs:
           key: ${{ runner.os }}-buildx-${{ github.sha }}
           restore-keys: |
             ${{ runner.os }}-buildx-
-      
+
       - name: Login to GitHub Container Registery
         uses: docker/login-action@v1
         with:
           registry: ghcr.io
           username: ${{ github.actor }}
           password: ${{ secrets.CR_PAT }}
-      
+
       - name: Push frontend to GitHub Container Registry
         uses: docker/build-push-action@v2
         with:
@@ -79,9 +80,9 @@ jobs:
 
       - name: Pull gitea image with current submodule SHA
         shell: bash
-        run : |
+        run: |
           docker pull ghcr.io/kitspace/gitea:${{ steps.sha.outputs.gitea_sha_short }} \
-            || exit 1
+            || echo 'Failed to pull, Gitea submodule has been updated! Building new image...' && exit 1
 
       - name: Push gitea to GitHub Container Registry
         # If the previous step failed, i.e., there's no image tagged gitea:${{gitea_sha_short}} in ghcr,
@@ -95,7 +96,14 @@ jobs:
           tags: ghcr.io/kitspace/gitea:${{ steps.sha.outputs.gitea_sha_short }}
           cache-from: type=local,src=/tmp/.buildx-cache
           cache-to: type=local,dest=/tmp/.buildx-cache
-      
+
+  push_to_registry_latest:
+    name: Run e2e & publish `latest` docker images
+    runs-on: ubuntu-20.04
+    needs:
+      - push_to_registry
+
+    steps:
       - name: Configure /etc/hosts
         shell: bash
         run: |
@@ -109,7 +117,7 @@ jobs:
       # ii. forward Nginx port 80 to internal port 3000. Keep the indentation!
       - name: Patch `docker-compose.deploy.yml`
         shell: bash
-        run: | 
+        run: |
           sed  -Ei \
             "s/ghcr.io\/kitspace\/(.*):([[:alnum:]]*)/ghcr.io\/kitspace\/\1:${{ steps.sha.outputs.sha_short }}/g" docker-compose.deploy.yml
           sed  -Ei \
@@ -117,7 +125,7 @@ jobs:
             docker-compose.deploy.yml
           sed -i "/'443:443'/a\      - \'${KITSPACE_DEV_PORT}:80\'" docker-compose.deploy.yml
           cat docker-compose.deploy.yml
-      
+
       - name: Install httpie
         shell: bash
         run: sudo apt install httpie
