CI: split run commands into multiple lines.

diff --git a/.github/workflows/publish-docker-images.yml b/.github/workflows/publish-docker-images.yml
--- a/.github/workflows/publish-docker-images.yml
+++ b/.github/workflows/publish-docker-images.yml
@@ -35,7 +35,8 @@ jobs:
         shell: bash
         run: |
           echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
-          echo "::set-output name=gitea_sha_short::$( git submodule foreach 'echo "$sha1"' | sed -n "/gitea/{N; p}" | sed '2q;d'| xargs git rev-parse --short )"
+          echo "::set-output name=gitea_sha_short::$( git submodule foreach 'echo "$sha1"' \
+            | sed -n "/gitea/{N; p}" | sed '2q;d'| xargs git rev-parse --short )"
 
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v1
@@ -78,7 +79,8 @@ jobs:
       - name: Pull gitea image with current submodule SHA
         shell: bash
         run : |
-          docker pull ghcr.io/kitspace/gitea:${{ steps.sha.outputs.gitea_sha_short }} || echo 'Failed to pull, Gitea submodule has been updated!'
+          docker pull ghcr.io/kitspace/gitea:${{ steps.sha.outputs.gitea_sha_short }} \
+            || echo 'Failed to pull, Gitea submodule has been updated! Building new image...'
 
       - name: Push gitea to GitHub Container Registry
         # If the previous step failed, i.e., there's no image tagged gitea:${{gitea_sha_short}} in ghcr,
@@ -107,8 +109,11 @@ jobs:
       - name: Patch `docker-compose.deploy.yml`
         shell: bash
         run: | 
-          sed  -Ei "s/ghcr.io\/kitspace\/(.*):([[:alnum:]]*)/ghcr.io\/kitspace\/\1:${{ steps.sha.outputs.sha_short }}/g" docker-compose.deploy.yml
-          sed  -Ei "s/ghcr.io\/kitspace\/gitea:${{ steps.sha.outputs.sha_short }}/ghcr.io\/kitspace\/\gitea:${{ steps.sha.outputs.gitea_sha_short }}/g" docker-compose.deploy.yml
+          sed  -Ei \
+            "s/ghcr.io\/kitspace\/(.*):([[:alnum:]]*)/ghcr.io\/kitspace\/\1:${{ steps.sha.outputs.sha_short }}/g" docker-compose.deploy.yml
+          sed  -Ei \
+            "s/ghcr.io\/kitspace\/gitea:${{ steps.sha.outputs.sha_short }}/ghcr.io\/kitspace\/\gitea:${{ steps.sha.outputs.gitea_sha_short }}/g" \
+            docker-compose.deploy.yml
           sed -i "/'443:443'/a\      - \'${KITSPACE_DEV_PORT}:80\'" docker-compose.deploy.yml
           cat docker-compose.deploy.yml
       
